### ISSUE TITLE
Windows certificate selection dialog

### ISSUE THREAD

**Issue by mlangenberg** [minvws/pUzi-python#5]
When a Windows computer is used by multiple people, the operating system remembers previously used certificates. Browsers (Chrome, Edge and Firefox) ask the user to select a certificate to verify their identity.

![image](https://user-images.githubusercontent.com/992/164540699-eb0c0246-668e-44f7-bda7-069c2a9fe289.png)

Of course, only one certificate corresponds to the UZI card that is currently in the smart card reader, and users need to enter their PIN to prove it is theirs, but from a usability perspective this is rather inconvenient.

Are their ways to circumvent this dialog? On macOS the user is only asked to confirm the UZI card that is actually in the reader, which is much more user friendly.

This is not specific to the implementation in this repository, but applies to all websites accepting UZI cards via client certificate authentication.

**Comment by gerbrand-bosch** [comment]
I'am sorry to inform you that we cannot assist you with your issue. This repository only adds the ability to a python backend to read and validate an UZI Client Certificate and does not focus on the browser and user interaction of the certificate selection.
